<?php
/* +-----------------------------------------------------------------------------+
 *    OpenEMR - Open Source Electronic Medical Record
 *    Copyright (C) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *    @author  Sanal Jacob <sanalj@zhservices.com>
 * +------------------------------------------------------------------------------+
 */
?>
<style>
    table.gridview2 td{
        border-style: dotted;
        border-width: 1px 1px 1px 1px;
        margin: 0;padding: 0;
        border-color:#cccccc;
    }
    table.thcolor th{
        background:linear-gradient(to bottom, #EFF5FF 0px, #E0ECFF 100%) repeat-x scroll 0 0 transparent;
        border: 1px solid #cccccc;
        height:10px;
        height:20px; 
    }
    #patdiv{
        position: absolute;
        left: 460px;
        border: 1px solid #95B8E7;
        display: none;
        min-width: 143px;
        background-color: #fff;
        margin: 0 6px;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        $(".datetimeclass").datetimepicker({
            showSecond: true,
            dateFormat: "yy-mm-dd",
            timeFormat: "hh:mm:ss",
            showOn: 'button',
            buttonImage: '<?php echo $this->basePath(); ?>/css/icons/calendar.gif',
            buttonImageOnly: true,
        });
        $(".dateclass").datepicker({
            dateFormat: "yy-mm-dd",
            showOn: 'button',
            buttonImage: '<?php echo $this->basePath(); ?>/css/icons/calendar.gif',
            buttonImageOnly: true,
        });
        $(".datetimeclass").on('change', function() {
            var x = $(this).val();
            if (!(x.match(/(\d{4})\-(0[1-9]|1[0-2])\-(0[1-9]|1[0-9]|2[0-9]|3[0-1])\s\d{2}:\d{2}:\d{2}/))) {
                alert("Invalid Date Format");
                $(this).val("");
            }
        });
        $(".dateclass").on('change', function() {
            var x = $(this).val();
            if (!(x.match(/(\d{4})\-(0[1-9]|1[0-2])\-(0[1-9]|1[0-9]|2[0-9]|3[0-1])/))) {
                alert("Invalid Date Format");
                $(this).val("");
            }
        });
<?php if ($this->layout()->saved == 'yes') { ?>
            alert('Successfully Saved');
<?php } ?>
    });
    function doSearch() {
        if ($("#search_patient").val() == '') {
            $("#patient_id").val('');
        }
        $("#specimen").submit();
    }
    function doSave() {
        $("#specimen").attr("action", window.location.href.replace("index", "save"));
        $("#specimen").submit();
    }
    function displayPopUp(labOrId)
    {
        window.location.assign("<?php echo $this->basePath(); ?>/lab/result/localrequisitionPdf?orderid=" + labOrId + "&save=yes", "Print", 'width=1000,height=800,resizable=yes,scrollbars=yes');
    }
</script>
<div style="margin:10px 0;"></div>
<div class="easyui-panel" title="<?php echo xlt('Sample Collection'); ?>" >
    <div style="padding:10px;">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('specimen', array('action' => 'index')));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <div>
            <div>
                <span class="bold mediumfont" >Date</span>
            </div>
            <div style="float:left;padding-right:10px;">
                <span><?php echo xlt('From') . ":&nbsp;";
        echo $this->formRow($form->get('search_from_date')); ?></span>
                <span><?php echo xlt('To') . ":&nbsp;";
        echo $this->formRow($form->get('search_to_date')); ?></span>
                <span style="padding-left:25px;"><?php echo xlt('Patient') . ":&nbsp;";
        echo $this->formRow($form->get('search_patient')); ?></span>
                <div id="patdiv" ></div>
        <?php echo $this->formRow($form->get('patient_id')); ?>
                <span style="padding-left:25px;"><?php echo xlt('Specimen Status') . ":&nbsp;";
        echo $this->formRow($form->get('specimen_search_status')); ?></span>
            </div>
            <a href="#" class="easyui-linkbutton" iconCls="icon-search" plain="true" onclick="doSearch()"><?php echo xlt('Search'); ?></a>
        </div>
        <br/>
        <a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="doSave()"><?php echo xlt('Save'); ?></a>
        <table id="specimentable" class="dv-table gridview2 thcolor" style="width:99%;height:auto;background:#ffffff;padding:5px;margin-top:5px;margin-bottom:15px;" >
            <tr>
                <th colspan="4" class="mainhead" ><?php echo xlt('Order');?></th>
                <th colspan="4" class="mainhead" ><?php echo xlt('Report');?></th>
            </tr>
            <tr>
                <td class="bold smallfont" style="width:40px;" ><?php echo xlt('PID');?></td>
                <td class="bold smallfont" style="min-width:80px;" ><?php echo xlt('Patient Name');?></td>
                <td class="bold smallfont" style="width:80px;" ><?php echo xlt('Order Date');?></td>
                <td class="bold smallfont" style="min-width:200px;" ><?php echo xlt('Name');?></td>
                <td class="bold smallfont" ><?php echo xlt('Specimen');?></td>
                <td class="bold smallfont" ><?php echo xlt('Specimen Time Collected');?></td>
                <td class="bold smallfont" ><?php echo xlt('Specimen Status');?></td>
                <td class="bold smallfont" title="<?php echo xlt('Download Requisition');?>" ><?php echo xlt('Req');?>.</td>
            </tr>
            <?php
            $ele_id = $form->get('specimen_collected_time[]')->getAttribute('id');
            $i = 0;
            $prev_ordid = '';
            foreach ($this->layout()->res as $val):
                $id = $ele_id . '_' . ++$i;
                ?>
                <tr>
                    <td><?php echo $val['patient_id']; ?></td>
                    <td><?php echo $val['pname']; ?></td>
                    <?php echo $this->formRow($form->get('procedure_order_id[]')->setValue($val['poid'])); ?>
                    <?php echo $this->formRow($form->get('procedure_order_seq[]')->setValue($val['poseq'])); ?>
                    <td><?php echo $val['date_ordered']; ?></td>
                    <td><?php echo $val['procedure_name']; ?></td>
                    <td><?php echo $this->formRow($form->get('specimen[]')->setValue($val['specimen_num'])); ?></td>
                    <td><?php echo $this->formRow($form->get('specimen_collected_time[]')->setAttribute('id', $id)->setValue($val['date_collected'])); ?></td>
                    <td><?php echo $this->formRow($form->get('specimen_status[]')->setValue($val['report_status'])); ?></td>
                    <?php if ($prev_ordid != $val['poid']) { ?>
                        <td><a href="#" onclick="displayPopUp('<?php echo $val['poid']; ?>')" > <img src="<?php echo $this->basePath() . '/css/icons/pdf_icon.png'; ?>" > </a></td>
                <?php } else { ?>
                        <td>&nbsp;</td>
                <?php } ?>
                </tr>
    <?php
    $prev_ordid = $val['poid'];
endforeach;
?>
        </table>
    </div>
</div>
<?php
echo $this->form()->closeTag();
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/lab/patient.js')
        ->prependFile($this->basePath() . '/js/lib/jquery.autocomplete.js')
        ->prependFile($this->basePath() . '/js/lib/jQuery.bubbletip-1.0.6.js')
        ->prependFile($this->basePath() . '/js/lib/bubbles.js')
?>